# Complexity thresholds
cognitive-complexity-threshold = 25
too-many-arguments-threshold = 10
type-complexity-threshold = 250
max-fn-params-bools = 3
max-struct-bools = 3
array-size-threshold = 16

# Import controls
warn-on-all-wildcard-imports = true

# Documentation requirements
doc-valid-idents = [
    "KiB", "MiB", "GiB", "TiB", "PiB", "EiB",
    "KB", "MB", "GB", "TB", "PB", "EB",
    "OAuth", "GraphQL", "OpenAPI", "REST", "HTTP", "HTTPS",
    "TCP", "UDP", "IP", "DNS", "TLS", "SSL",
    "JSON", "YAML", "TOML", "XML", "CSV",
    "PostgreSQL", "MySQL", "SQLite", "Redis",
    "GitHub", "GitLab", "BitBucket",
    "JavaScript", "TypeScript", "WebAssembly", "WASM",
    "API", "APIs", "CLI", "UI", "UUID", "JWT",
    "ASCII", "UTF", "ISO",
    "ID", "IDs"
]
missing-docs-in-crate-items = true

# Error handling and safety
disallowed-methods = [
    "std::option::Option::unwrap",
    "std::result::Result::unwrap"
]

# Testing and development aids
allow-unwrap-in-tests = true
allow-expect-in-tests = true
allow-panic-in-tests = true

# Performance thresholds
pass-by-value-size-limit = 128
unnecessary-box-size = 512
vec-box-size-threshold = 512

# Async/await safety
await-holding-invalid-types = []

# Code organization
check-private-items = true

# Additional safety checks
arithmetic-side-effects-allowed = []
arithmetic-side-effects-allowed-binary = []
arithmetic-side-effects-allowed-unary = []

# Type system
max-trait-bounds = 3
enforce-iter-loop-reborrow = true

# Security considerations
enable-raw-pointer-heuristic-for-send = true

# Tracing and logging configuration
ignore-interior-mutability = [
    "tracing::Span",
    "tracing::Event",
    "tracing_subscriber::Layer",
    "tracing::Subscriber",
    "log::Record",
    "log::Metadata"
]
